name = "spike"
defaultTargets = ["Spike", "Idol"]

[[lean_lib]]
name = "Spike"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation"
rev = "f212e81484a045697b3f6f171adf28fb57c750fc"

[[lean_lib]]
name = "Idol"
